services:
  - type: web
    name: phpmyadmin
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PMA_HOST
        value: shuttle.proxy.rlwy.net
      - key: PMA_PORT
        value: 21840
      - key: PMA_USER
        value: root
      - key: PMA_PASSWORD
        value: anJkMDnhTJoXaMDjgYFpfmkMBUskRZFu